Create form
laiifuu/Free-code-camp-form pull request #2
Opened 2022-08-26 21:37 UTC by laiifuu

In this PR,I: 
- Created a form and styled it.

2022-08-26 22:04 UTC, laiifuu commented on css/style.css
> + border: 1px solid black;
Please remember to remove this line after you are done with your work.

2022-08-26 22:16 UTC, laiifuu commented on css/style.css
> +}
Please add a margin of 100% to the input selector.

2022-08-26 22:22 UTC, laiifuu reviewed
Hi there @laiifuu 

Good job so far, the structure of the page is there, but the styling could use some more work. There are some issues that you need to work on. Don't worry, you got this !

## Highlights

- [x] Descriptive pull request. 

![tumblr_2c17ed43af0c76d62a10f3cde81be0c3_19247276_1280](https://user-images.githubusercontent.com/93520178/186996345-02c07a73-4277-4560-90a7-e833da685a26.gif)

## Required Changes ♻️

- You have linter errors, so please make sure you resolve those. 
![linter errors](https://user-images.githubusercontent.com/93520178/186996941-00981a39-3c6e-481f-935c-df75fd3b79c8.PNG)

- Since your work is incomplete, please refer to this article to learn how to style forms: 
https://developer.mozilla.org/en-US/docs/Learn/Forms/Styling_web_forms 

Also, check the comments under the review.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please remember to tag me in your question so I can receive the notification.

2022-08-26 22:34 UTC, Ugboaja-Uchechi requested changes
Hi @laiifuu, 

Good job so far!
There are some issues that you still need to work on to go to the next project but you are almost there!

## Highlights

- Good use of GitHub Features ✔️ 
- Inline comments were used👍 

## Required Changes ♻️

- [ ] Great job giving your first review at Microverse 👏. When giving a review it's best to explain to the student why the review was given so they can understand your review better. Kindly include an explanation, a "why", for each requested change  🙏 

_Check the comments under the review._

## Optional suggestions
_Every comment with the [OPTIONAL] prefix is not crucial enough to stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 08:24 UTC, emmiiorji commented
Hi @laiifuu, 

# Status: Approved ✅

You've done great at reviewing this project!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Good Highlights ✅

- You implemented suggested changes
- Your reviews are in kind tones
- You made good suggestions for improving the project

## Optional suggestions

- I suggest that use use gifs with lesser commanding tone. Even though the gif wasn't made by you, you might get misunderstood.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 08:26 UTC, emmiiorji approved these changes
Hi @laiifuu, 

# Status: Approved ✅

You've done great at reviewing this project!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

![Well Done](https://user-images.githubusercontent.com/20554583/187022030-7b118492-6158-4851-97cf-afefec99a4c8.gif)

## Good Highlights ✅

- You implemented suggested changes
- Your reviews are in kind tones
- You made good suggestions for improving the project

## Optional suggestions

- I suggest that use use gifs with lesser commanding tone. Even though the gif wasn't made by you, you might get misunderstood.

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2022-08-27 08:34 UTC, merged